### ISSUE TITLE
some issues about the keywords USER_AGENT

### ISSUE THREAD

**Issue by leyiwang** [jonbakerfish/TweetScraper#1]
Excuse me, can you give me an example about the keywords USER_AGENT? 
if i want to get some twitters with the emotion signs ":)" from Apri, 2013  on the website twitter, what should i set about the keywords USER_AGENT in the setting file?

**Comment by jonbakerfish** [comment]
It doesn't matter what you search when setting the `USER_AGENT`. You can simply set it to your email.

Your searching command could look like:

    scrapy crawl TweetScraper -a queries=":) since:2013-04-01"
