### ISSUE TITLE
how can i save to mysql

### ISSUE THREAD

**Issue by ihahawen** [jonbakerfish/TweetScraper#101]
i find "settings.py " is not    " 'TweetScraper.pipelines.SavetoMySQLPipeline':100," When  I add it, and find "pipelines.py"
 is not "class SavetoMySQLPipeline(object):" ,when i add it, "NameError: name 'mysql' is not defined"

**Comment by ihahawen** [comment]
i can save data to jsonfile

**Comment by ihahawen** [comment]
i use "pip install mysql-connector",no  "NameError: name 'mysql' is not defined"

**Comment by ihahawen** [comment]
But there are other problems

Traceback (most recent call last):
  File "/Users/wen/anaconda3/envs/tweetscraper/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/wen/anaconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/utils/defer.py", line 157, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/Users/wen/Documents/GitHub/TweetScraper/TweetScraper/pipelines.py", line 171, in process_item
    self.insert_one(dict(item))  # Item is inserted or updated.
  File "/Users/wen/Documents/GitHub/TweetScraper/TweetScraper/pipelines.py", line 123, in insert_one
    ret = self.check_vals(item)
  File "/Users/wen/Documents/GitHub/TweetScraper/TweetScraper/pipelines.py", line 90, in check_vals
    ID = item['ID']
KeyError: 'ID'

**Comment by ihahawen** [comment]
i think items.py delete 
class Tweet(Item):
    ID = Field()       # tweet id
    url = Field()      # tweet url
    datetime = Field() # post time
    text = Field()     # text content
    user_id = Field()  # user id
    usernameTweet = Field() # username of tweet

    nbr_retweet = Field()  # nbr of retweet
    nbr_favorite = Field() # nbr of favorite
    nbr_reply = Field()    # nbr of reply

    is_reply = Field()   # boolean if the tweet is a reply or not
    is_retweet = Field() # boolean if the tweet is just a retweet of another tweet

    has_image = Field() # True/False, whether a tweet contains images
    images = Field()    # a list of image urls, empty if none

    has_video = Field() # True/False, whether a tweet contains videos
    videos = Field()    # a list of video urls

    has_media = Field() # True/False, whether a tweet contains media (e.g. summary)
    medias = Field()    # a list of media

**Comment by ihahawen** [comment]
How do I need to modify it，“TweetScraper/TweetScraper/spiders/TweetCrawler.py”

**Comment by ihahawen** [comment]
i know where is wrong，i test it
“
    def parse_tweet_item(self, items):
        for k,v in items.items():
            # assert k == v['id_str'], (k,v)
            tweet = Tweet()
            
            tweet['id_'] = k
            print(tweet['id_'])
            tweet['raw_data'] = v
            print(tweet['raw_data'])
            tweet['datetime']='datetime'
            tweet['url']='url'
            tweet['ID']='ID'
            tweet['text']='text'
            tweet['user_id']='user_id'
            tweet['usernameTweet']='usernameTweet'
            yield tweet
”
i can write something ，and insert mysql

**Comment by ihahawen** [comment]
how to parse the twitter items into the mysql???
def parse_tweet_item(self, items):

**Comment by ihahawen** [comment]
![image](https://user-images.githubusercontent.com/37093010/95304149-c2311a00-08b6-11eb-9f2f-08e0ac64ac98.png)
I think i done it

**Comment by ihahawen** [comment]
But i can't catch the screen_name from "data = json.loads(response.text)"

**Comment by ihahawen** [comment]
![image](https://user-images.githubusercontent.com/37093010/95312282-50aa9900-08c1-11eb-8c06-92da854d279a.png)
Why appear this problem？

**Comment by ihahawen** [comment]
When add save data to mysql ?

**Comment by fireint** [comment]
> But there are other problems
> 
> Traceback (most recent call last):
> File "/Users/wen/anaconda3/envs/tweetscraper/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
> current.result = callback(current.result, *args, **kw)
> File "/Users/wen/anaconda3/envs/tweetscraper/lib/python3.7/site-packages/scrapy/utils/defer.py", line 157, in f
> return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
> File "/Users/wen/Documents/GitHub/TweetScraper/TweetScraper/pipelines.py", line 171, in process_item
> self.insert_one(dict(item)) # Item is inserted or updated.
> File "/Users/wen/Documents/GitHub/TweetScraper/TweetScraper/pipelines.py", line 123, in insert_one
> ret = self.check_vals(item)
> File "/Users/wen/Documents/GitHub/TweetScraper/TweetScraper/pipelines.py", line 90, in check_vals
> ID = item['ID']
> KeyError: 'ID'

how did you solve this error plz?

**Comment by gxwyz** [comment]
> ID = item['ID']

You must edit "items.py" like this:

class Zhiku2Item(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field() 

edit in pipeline.py:
add "from zhiku2.items import Zhiku2Item"

edit in srcpa***.py like this:
....................
    def parse(self, response):
        item = Zhiku2Item()
        div_list = response.xpath("//div[@class='views-row']/section/div")
....................
