### ISSUE TITLE
TCP connection timed out: 10060

### ISSUE THREAD

**Issue by callaaaa** [jonbakerfish/TweetScraper#104]
[1010/193845.588:INFO:CONSOLE(0)] "ResizeObserver loop limit exceeded", source: https://twitter.com/explore (0)
2020-10-10 19:39:42 [scrapy.extensions.logstats] INFO: Crawled 1 pages (at 1 pages/min), scraped 0 items (at 0 items/min)
2020-10-10 19:39:48 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mu
te_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_co
lor=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&query_source=typed_query&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel&count=20&q=happy%20hour> (failed 3 times): TCP connection timed out: 10060: 由于连接方
在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2020-10-10 19:39:48 [scrapy.core.scraper] ERROR: Error downloading <GET https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&incl
ude_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&inclu
de_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&query_source=typed_query&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel&count=20&q=happy%20hour>
Traceback (most recent call last):
  File "d:\python36\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    return (yield download_func(request=request, spider=spider))
twisted.internet.error.TCPTimedOutError: TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
2020-10-10 19:39:48 [scrapy.core.engine] INFO: Closing spider (finished)
2020-10-10 19:39:50 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 3,
 'downloader/exception_type_count/twisted.internet.error.TCPTimedOutError': 3,
 'downloader/request_bytes': 5650,
 'downloader/request_count': 3,
 'downloader/request_method_count/GET': 3,
 'downloader/response_bytes': 60957,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 66.109241,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 10, 10, 11, 39, 48, 414918),
 'log_count/ERROR': 2,
 'log_count/INFO': 11,
 'request_depth_max': 1,
 'response_received_count': 1,
 'retry/count': 2,
 'retry/max_reached': 1,
 'retry/reason_count/twisted.internet.error.TCPTimedOutError': 2,
 'scheduler/dequeued': 4,
 'scheduler/dequeued/memory': 4,
 'scheduler/enqueued': 4,
 'scheduler/enqueued/memory': 4,
 'start_time': datetime.datetime(2020, 10, 10, 11, 38, 42, 305677)}
2020-10-10 19:39:50 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by aaryanwang** [comment]
Are you sure your internet connection is ok？@callaaaa

**Comment by callaaaa** [comment]
@aaryanwang  I can visit twitter through my browser directly.And I check my geckodriver's content:
`1602593399566	geckodriver	INFO	Listening on 127.0.0.1:54636
1602593402578	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.EXE" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "C:\\Users\\someone\\AppData\\Local\\Temp\\rust_mozprofile5ZnHI4"
*** You are running in headless mode.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
console.error: SearchCache: "_readCacheFile: Error reading cache file:" (new Error("", "(unknown module)"))
1602593406770	Marionette	INFO	Listening on port 54646
1602593406862	Marionette	WARN	TLS certificate errors will be ignored for this session
console.error: Region.jsm: "Error fetching region" (new AbortError("The operation was aborted. ", (void 0), 697))
console.error: Region.jsm: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.jsm", 351))
1602593480279	Marionette	INFO	Stopped listening on port 54646
`
are there some clues to solve my problem?thanks.

**Comment by zhuzhu-lu** [comment]
同样的问题，求问
