### ISSUE TITLE
Error Language Setting 

### ISSUE THREAD

**Issue by SofyaMa** [jonbakerfish/TweetScraper#110]
Does anybody know, what has happened, the following line used to work before:
scrapy crawl TweetScraper -a query="#hahaha since:2020-04-30 until:2020-05-05 tweet_search_mode=live" -a lang="en"
 
And now I get the following error:

TypeError: __init__() got an unexpected keyword argument 'lang'

Thank you!!

**Comment by SofyaMa** [comment]
crawl: error: running 'scrapy crawl' with more than one spider is no longer supported

**Comment by FFCA** [comment]
Is there a way to change the language?
