### ISSUE TITLE
Combining Tweet and user data

### ISSUE THREAD

**Issue by M-I-Dx** [jonbakerfish/TweetScraper#117]
I am collecting tweets regarding a specific topic and was hoping to combine the user data with the tweet data. 

- What changes to the code would you suggest so that each tweet file also has the user data? 
- Is the Id in user data equivalent to the user_id in the tweet data?

**Comment by bilal-athar** [comment]
> I am collecting tweets regarding a specific topic and was hoping to combine the user data with the tweet data.
> 
> * What changes to the code would you suggest so that each tweet file also has the user data?
> * Is the Id in user data equivalent to the user_id in the tweet data?

If you want to combine tweet and user data why don't you change the path in the settings.py file. Select the same path for both users and tweets.
Yes, the id in the user's data is equivalent to the user_id in tweets data.
