### ISSUE TITLE
No module named sgmllib

### ISSUE THREAD

**Issue by InnovativeCoder** [jonbakerfish/TweetScraper#12]
After exectuing the command scrapy crawl Tweetcraper -a query=example , it is showing an error that no module named sgmllib is found. I have installed latest module of scrapy and they are saying that sgmllib is depricated. Please help!!

**Comment by fauzanbaigm** [comment]
Sorry for the delayed response. Have included a fix for the above issue (pull request below). Moderators or Reviewers do look into it. 

https://github.com/jonbakerfish/TweetScraper/pull/14

**Comment by fauzanbaigm** [comment]
Issue has been following the last merge. Kindly validate it and close the issue.
