### ISSUE TITLE
Saving tweets with SaveToFilePipeline creates too many files

### ISSUE THREAD

**Issue by ckingdev** [jonbakerfish/TweetScraper#16]
So I've been hacking on this the past few days, this project has been very helpful. I've needed to collect large numbers of tweets and users, and this has been the only feasible tool.

However, when scraping large numbers of objects, having one file per tweet/user is a serious problem. 

1. It wastes a huge amount of space. I had 230k files that averaged a bit under 390 bytes each, however, each file occupied the block size of my drive- 4kb. So the disk usage for me is >10x the actual size of the data.

2. It breaks many of the tools that someone might use to fix this. `cat`, `ls`, `find`, etc all break. My graphical file manager hung. I eventually figured out a solution, in case anyone ends up needing it, but this really shouldn't happen.

```bash
ls | xargs cat > output
```

It's very unexpected and unpleasant behavior. I've put together a solution that saves tweets and users to their respective configured paths as newline-delimited json. The files are opened with mode a+ so they can be closed properly and flushed in between saves and they won't truncate an existing file.

For the issue of duplication, I'm just holding a set of user/tweet IDs in memory.  At 64 bits each, even at 100 million IDs the memory cost is less than 1 GB, The only issue I have left is finding a way to persist the IDs that have been scraped across sessions without having to read in the full amount of data that was saved previously. I'll want to polish it and make sure all is well, but I'd be happy to make a PR and discuss.

Thanks!

**Comment by jonbakerfish** [comment]
Did you try using mongodb to save your data? All you need is to install mongodb and [change the pipeline](https://github.com/jonbakerfish/TweetScraper/blob/master/TweetScraper/settings.py#L15).
Besides, the mongodb will use the ID of user/tweet as index and ensure they are unique. [see `pipelines.py`](https://github.com/jonbakerfish/TweetScraper/blob/master/TweetScraper/pipelines.py#L23)

BTW, you can use [mongo-hacker](https://github.com/TylerBrock/mongo-hacker) for better UX when looking into the data.

**Comment by ckingdev** [comment]
I looked at the that file plenty, but that doesn't change the fact that the default pipeline is broken and there's no documentation. If you read what I wrote, I have my problem solved. I was offering to clean up the code and make a pull request. I don't need mongo to store this, I'd just have to pull everything out and dump it to disk as json anyway.

**Comment by fauzanbaigm** [comment]
@ckingdev - _default pipeline is broken_ is not entirely correct, if you understood how **scrapy worked**. And one of the reason why DB interaction is simpler because of not having to do this manually manipulating of storing data in files. 

However, to make your work a bit simpler - you could have just removed the pipeline flow i.e removed **yield** at line numbers: **151 & 161** with file insertion logic. This would have worked for your specific use case. 

> Introducing this logic in the package entirely is not suggested as the DB interaction is more elegant and this design should be encouraged.
