### ISSUE TITLE
Not running with some combinations of queries

### ISSUE THREAD

**Issue by simonlindgren** [jonbakerfish/TweetScraper#18]
I have noticed some odd behaviour with this, otherwise great, scraper.

- `query='monkey,coffee'` runs with no problems.
- `query='monkey,#coffee'` runs with no problems.
- `query='#monkey,#coffee'` breaks.
- `query='#monkey,#coffee,#love,#gorilla'` breaks.
- `query='monkey,#coffee,love,gorilla'` breaks.
- `query='monkey,coffee,love,#gorilla'` breaks.
- `query='#monkey,coffee,love,gorilla'` breaks.
- `query='monkey,coffee,love,#gorilla'` breaks.
- `query='monkey,coffee,love,gorilla'` breaks.
- `query='monkey,coffee,love'` runs with no problems.
- `query='monkey,coffee,#love'` breaks.
- `query='#love'` runs with no problems.

**Tentative conclusions**
- We can use no more than three keywords at the same time.
- Hashtag searches can only be one hashtag per search, combined with a maximum of one other (non-hashtag) search word.

There is probably some underlying thing that I am missing here...?

**Comment by jonbakerfish** [comment]
What is the spider's output error message? I tested `query='monkey,coffee,love,gorilla'`, and it returned 2 tweets. If you search these keywords on [Twitter Search](https://twitter.com/search?q=monkey%20coffee%20love%20gorilla&src=typd). It shows that there are only 2 tweets.

**Comment by simonlindgren** [comment]
So, maybe I have misunderstood what the expected output should be. The instances that I have perceived as not working may just be very very short scraping jobs. It seems then that the queries are joined together by an `AND` logic (rather than `OR`). Am I right?

**Comment by jonbakerfish** [comment]
Yes. The whole query will send to twitter search directly ( see [TweetCrawler.py#L39](https://github.com/jonbakerfish/TweetScraper/blob/master/TweetScraper/spiders/TweetCrawler.py#L39) )

**Comment by simonlindgren** [comment]
Yes, of course! I see that now. Consequently:

`query='monkey OR coffee OR love OR #gorilla'`

is what I was looking for, and it also works. I clarified this in my post on your excellent scraper: http://www.simonlindgren.com/stuff/2017/11/7/scrape-tweets-without-using-the-api

**Comment by jonbakerfish** [comment]
Glad it help your work and thanks for sharing. Closing the issue now.
