### ISSUE TITLE
running 'scrapy crawl' with more than one spider is no longer supported

### ISSUE THREAD

**Issue by Hellofafar** [jonbakerfish/TweetScraper#19]
Hi,

I try to run the command `scrapy crawl TweetScraper -a query=bitcoin since: 2017-01-01 until: 2017-01-01` to retrieve the tweets, but I got following error: crawl: error: running 'scrapy crawl' with more than one spider is no longer supported.

What's more, when I not designate the date, it will retrieve too much tweets for me in one day. Can I set a limit for the tweets of every single day, e.g 1000 tweets per day?

Thanks!

**Comment by jonbakerfish** [comment]
>  I got following error: crawl: error: running 'scrapy crawl' with more than one spider is no longer supported.

You should quote the query `query="bitcoin since:2017-01-01 until:2017-01-02"`.

> Can I set a limit for the tweets of every single day, e.g 1000 tweets per day?

No. You need to filter the tweets by yourself.

**Comment by Hellofafar** [comment]
Thanks, it's helpful!
