### ISSUE TITLE
Missing many tweets...?

### ISSUE THREAD

**Issue by zacheberhart** [jonbakerfish/TweetScraper#2]
This doesn't seem to be scraping all of the tweets when using date filters...

Is it only scraping "Top" tweets? If so, is there anyway that I can change it to "All"?

Thank you!
Zach

**Comment by jonbakerfish** [comment]
The crawler is outdated because Twitter change its html & css regularly. 
You have to read their code and modify the [TweetCrawler.py](https://github.com/jonbakerfish/TweetScraper/blob/master/TweetScraper/spiders/TweetCrawler.py) accordingly.
