### ISSUE TITLE
Nothing is saving into the Data folder

### ISSUE THREAD

**Issue by tomtaila** [jonbakerfish/TweetScraper#20]
Trying to use this but nothing is being saved - I even tried the simple 
"scrapy crawl TweetScraper -a query=foo,#bar"
but that didn't save either

**Comment by pseudomonas** [comment]
Tweetscraper used to work but I think the data format that Twitter returns must have changed recently; it all stopped working I think at some point in the first half of December 2017,

**Comment by sqlballs** [comment]
Hi All, It took me a while to work through this.  But the error is in the ID which is essential to the whole script.  The path was changed from username u-dir to username u-dir u-textTruncate.  So if you change the following line in TweetCrawler.py from:

tweet['usernameTweet'] = item.xpath('.//span[@class="username u-dir"]/b/text()').extract()[0]

to

tweet['usernameTweet'] = item.xpath('.//span[@class="username u-dir u-textTruncate"]/b/text()').extract()[0]

This should start working .

Cheers!

**Comment by jonbakerfish** [comment]
@sqlballs  Thanks for pointing out! I have revise the code in this [commit](https://github.com/jonbakerfish/TweetScraper/commit/93423a1a0a1f5a695696b538dfa2a3f86b51ca99), please update and check it out.

**Comment by tomtaila** [comment]
@jonbakerfish @sqlballs Thanks guys! Great work on this project btw :)
