### ISSUE TITLE
Could not scrap tweets

### ISSUE THREAD

**Issue by emrecalisir** [jonbakerfish/TweetScraper#22]
Hi, 

When I start crawling, it continously creates error logs starting with the words "Error tweet". As a result, it cannot scrap any tweet succesfuly.  My log level is in ERROR.  What could be the problem? Is there any major change in general structure of Tweets, which causes to the errors during parsing operation? 

 [TweetScraper.spiders.TweetCrawler] ERROR: Error tweet: <div class="tweet js-stream-tweet js-actionable-tweet js-profile-popup-actionable dismissible-content
       original-tweet js-original-tweet

  has-cards  has-content
a-tweet-id="748650033210265600" data-item-id="748650033210265600" data-permalink-path="/rmc_lee/status/748650033210265600" data-conversation-id="748650033210265600"
tweet-nonce="748650033210265600-93347977-5360-4fdc-b571-8c945f28a106" data-tweet-stat-initialized="true" data-screen-name="rmc_lee" data-name="Jonathan" data-user-id
0161618" data-you-follow="false" data-follows-you="false" data-you-block="false" data-reply-to-users-json='[{"id_str":"1030161618","screen_name":"rmc_lee","name":"Jo
n","emojified_name":{"text":"Jonathan","emojified_text_as_html":"Jonathan"}}]' data-disclosure-type="" data-has-cards="true" data-component-context="tweet">

div class="context">

/div>

div class="content">

.
..
.
.
.

**Comment by jonbakerfish** [comment]
What's your command?

**Comment by emrecalisir** [comment]
scrapy crawl TweetScraper -a "query=#brexit since:2016-06-01 until:2016-07-01" -a crawl_user=True

**Comment by jonbakerfish** [comment]
Is your code up-to-date? I can run the following command without errors:

    scrapy crawl TweetScraper -a query="#brexit since:2016-06-01 until:2016-07-01" -a crawl_user=True
    scrapy crawl TweetScraper -a query="#brexit" -a crawl_user=True

**Comment by emrecalisir** [comment]
Thank you, it worked after getting latest code. I compared the differences between local and git code, the only difference was missing extTruncate field in 67th line. Thanks again.
