### ISSUE TITLE
MYSQL single quote insert error

### ISSUE THREAD

**Issue by TomLDennison** [jonbakerfish/TweetScraper#30]
When the SavetoMySQLPipeline class in the pipelines.py file tries to insert a record with a single quote, an error is being thrown and the record is rejected.  This is because MySQL throws single quotes to begin and end a string value in its insert statement.  In order to insert a string with a quote you must use '' (two single quotes in a row).  The bad insert statement is being created on line 141 of the pipelines.py file.  To fix this I updated the code on line 135:

text = item['text']

with the following code to replace each single quote with two single quotes:

text = item['text'].replace('\'', '\'\'')

This could be added to the other variables there for completeness, but wasn't necessary in my case.  

Thanks for publishing this!

**Comment by saggel** [comment]
I'm not sure if it's the same error, but I do get an error when using MySQL:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

the "near" part of the error is the tweet.

I tried the replacement you suggested, btw the write way I think is:
`text = item['text'].replace('', "")`

but it doesn't solve the problem for me!

**Comment by saggel** [comment]
An update on this, and hope @jonbakerfish can help:

Seems I get this error on tweets that have an apostrophe in the text.

So maybe _-with all caution that I might be wrong-_ something is not escaped properly in the code.

**Comment by saggel** [comment]
update on this - I corrected the replacement code and now it works for me!
