### ISSUE TITLE
Use of lang

### ISSUE THREAD

**Issue by saggel** [jonbakerfish/TweetScraper#31]
How can I use the lang part in the query?

I've tried all possible ways I can think but it doesn't work. In most combinations doesn't do anything, and in this, it looks like it's working but it doesn't scrape anything:

`scrapy crawl TweetScraper -a query="@foo -a lang['en']"`

thanks in advance

**Comment by jonbakerfish** [comment]
The format of using parameters should be `-a PARAM="value"`:
`scrapy crawl TweetScraper -a query="@foo" -a lang="fr"`

**Comment by saggel** [comment]
Thank you! It works!
