### ISSUE TITLE
Retweets not crawling

### ISSUE THREAD

**Issue by Monnerford** [jonbakerfish/TweetScraper#37]
I am having trouble crawling a user which I know has retweets: all the scraped tweets have an is_retweet=False, which means retweets are not scraped. Is that fixed in any known way?

**Comment by HJoentgen** [comment]
Have you been able to figure it out by now?

**Comment by ElisonSherton** [comment]
I am also suffering the same issue. I want to extract retweets from a user but cannot. Can anyone help out please?

**Comment by sscanavini** [comment]
Just add "include:nativeretweets" in your query
