### ISSUE TITLE
from scrapy.conf import settings exceptions.ImportError: No module named conf

### ISSUE THREAD

**Issue by jeromecc** [jonbakerfish/TweetScraper#57]
Hi!

There is no module scrapy.conf
scrapy.conf.settings is deprecated since 2014 per https://github.com/scrapy/scrapy/commit/993b543e1b895772ec8ac1aeb8db5a87d2b5f784#diff-5fa56a6cbc91c5af447e69c97083d78e

I could solve the bug by following this https://stackoverflow.com/questions/54717251/scrapydeprecationwarning-module-scrapy-conf-is-deprecated-use-crawler-setti

```
from scrapy.utils.project import get_project_settings
SETTINGS = get_project_settings()
```

Thanks for sharing your scraper with a free software license.

**Comment by mayankgautam** [comment]
@jeromecc Please can you tell me which file you edited to fix the issue.
