### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by jasontweet** [jonbakerfish/TweetScraper#62]
I run TweetScraper on Python 2.7 and dump the tweets into the filesystem. I noticed that the tweet texst contains no emoji codes. It seems that TweetCralwer.py does not extract emojis from the tweet texts. What am I doing wrong?

**Comment by ElisonSherton** [comment]
Same here. Any success on getting emojis using TweetScraper? I would be grateful if you could help me with this.
