### ISSUE TITLE
What does "100" mean here? 'TweetScraper.pipelines.SaveToFilePipeline':100

### ISSUE THREAD

**Issue by lmy931** [jonbakerfish/TweetScraper#66]
Dear developer,

I found this in the setting.py: 'TweetScraper.pipelines.SaveToFilePipeline':100,
I understand that it means we can choose to save to files or save to database, but what does that "100" mean?  Can you please give me a hint. Thanks.

Regards

**Comment by jonbakerfish** [comment]
See https://doc.scrapy.org/en/latest/topics/item-pipeline.html#activating-an-item-pipeline-component

> To activate an Item Pipeline component you must add its class to the ITEM_PIPELINES setting, like in the following example:

```
ITEM_PIPELINES = {
    'myproject.pipelines.PricePipeline': 300,
    'myproject.pipelines.JsonWriterPipeline': 800,
}
```

> The integer values you assign to classes in this setting determine the order in which they run: items go through from lower valued to higher valued classes. It’s customary to define these numbers in the 0-1000 range.
