### ISSUE TITLE
Current TweetScrape misses retweets in some situations

### ISSUE THREAD

**Issue by shiwenThu** [jonbakerfish/TweetScraper#71]
The current TweetScraper may miss several tweets in  some situations:
**In Case A and B,  the retweets will NOT be collected by using keyword "BBC" as input.**
Case A: "I don't agree with you! RT @realDonaldTrump: BBC always lies"
Case B: "RT @realDonaldTrump: BBC always lies"

**Only in Case C and D,  can tweets be collected  by using keyword "BBC" as input.**
Case C: "BBC did not lie! RT @realDonaldTrump: MAGA blablabla..."
Case D: "BBC did not lie!"

In a word, if original tweets contain the keyword, but the retweets do not contain keywords in the new text, the tweets cannot be acquired. This problem may be serious in some situations when several researchers want to explore the diffusion of information or the retweet network. But it seems Twitter API work well in case A and case B.

It's a great work and look forward for further solution !!!(I haven't found solutions).

**Comment by jonbakerfish** [comment]
The TweetScraper basically collects searching results from the https://twitter.com/search-home. 
So if you want to get the retweets, you can implement a different pipeline to collect all the retweets by given a tweet's id, which is similar to the workflow you click on each tweet page (i.e. https://twitter.com/USER/status/TWEET_ID) and scroll down to view all the replies.
