### ISSUE TITLE
Suggestion: Adding instructions on how to run inside of script

### ISSUE THREAD

**Issue by kallewesterling** [jonbakerfish/TweetScraper#72]
It would be really useful for the instructions on how to use TweetScraper to include how to run the spider using `scrapy` inside a script (or in my case, a Jupyter notebook/lab). Would that be possible?

**Comment by wwang184** [comment]
In Jupyter Notebook, the way I did it is to use shell command in the cell, such as:
```
query = f'scrapy crawl TweetScraper -a query="#{ticker} since:2019-01-01 until:2019-12-31"'
!$query
```
An official instruction would be really helpful for me, too.

**Comment by kallewesterling** [comment]
Yeah, there should be a more elegant solution...

**Comment by jonbakerfish** [comment]
Are you trying to [call an external command from Python](https://stackoverflow.com/questions/89228/calling-an-external-command-from-python)?
