### ISSUE TITLE
Problem parsing with exact phrases

### ISSUE THREAD

**Issue by wrmeyer** [jonbakerfish/TweetScraper#73]
I'll do a search like the following:

scrapy crawl TweetScraper -a query='"llamas are the best animal",since:2018-1-1' 
or 
scrapy crawl TweetScraper -a query="llamas are the best animal",since:2018-1-1

The date function works fine, but it'll pull all tweets as long as they have the individual words somewhere throughout the tweet. Even without the "since:xxxx-x-x" it won't work. For example if the text of the tweet was "did you know best was the are llamas animal," the tweet gets pulled even though its not the exact phrase I'm looking for. Thanks for any help.

**Comment by wrmeyer** [comment]
If someone could leave an example of the correct syntax I would be eternally grateful.

**Comment by saggel** [comment]
The correct syntax is:

`scrapy crawl TweetScraper -a "query=#llamas since:2019-01-01 until:2018-01-02" -a lang="en"`

added the last lang bit in case you need it!

**Comment by wrmeyer** [comment]
@saggel thank you, but this isn't what I was looking for. I'm having trouble looking for tweets with phrases of more than one word.

**Comment by satriabagsp** [comment]
@wrmeyer I have the same issue. Have you found the answer?

**Comment by wrmeyer** [comment]
@satriabagsp Unfortunately not. I'll comment here if I do though.
