### ISSUE TITLE
Error "Gave up Trying" Noob problem 

### ISSUE THREAD

**Issue by SofyaMa** [jonbakerfish/TweetScraper#80]
[scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://twitter.com/i/search/timeline?l=de&f=tweets&q=%23covid19&src=typed&max_position=thGAVUV0VFVBaCwL35r9SG2CIWgsC04bS519siEjUAFQAlAFUAFQAA> (failed 3 times): 429 Unknown Status
2020-04-16 16:07:40 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <429 https://twitter.com/i/search/timeline?l=de&f=tweets&q=%23covid19&src=typed&max_position=thGAVUV0VFVBaCwL35r9SG2CIWgsC04bS519siEjUAFQAlAFUAFQAA>: HTTP status code is not handled or not allowed
2020-04-16 16:07:40 [scrapy.core.engine] INFO: Closing spider (finished)
2020-04-16 16:07:40 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 646393,
 'downloader/request_count': 723,
 'downloader/request_method_count/GET': 723,
 'downloader/response_bytes': 15046598,
 'downloader/response_count': 723,
 'downloader/response_status_count/200': 720,
 'downloader/response_status_count/429': 3,
 'elapsed_time_seconds': 543.753948,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 4, 16, 14, 7, 40, 107301),
 'httperror/response_ignored_count': 1,
 'httperror/response_ignored_status_count/429': 1,
 'item_scraped_count': 14378,
 'log_count/ERROR': 1,
 'log_count/INFO': 20,
 'memusage/max': 80863232,
 'memusage/startup': 55848960,
 'request_depth_max': 720,
 'response_received_count': 721,
 'retry/count': 2,
 'retry/max_reached': 1,
 'retry/reason_count/429 Unknown Status': 2,
 'scheduler/dequeued': 723,
 'scheduler/dequeued/memory': 723,
 'scheduler/enqueued': 723,
 'scheduler/enqueued/memory': 723,
 'start_time': datetime.datetime(2020, 4, 16, 13, 58, 36, 353353)}
2020-04-16 16:07:40 [scrapy.core.engine] INFO: Spider closed (finished)

What to do with this error? I am stuck here, can I somehow start scraping from the last scraped tweet on? Please help me guys.

Thanks a lot!

**Comment by carlafdzzz** [comment]
I have the same issue, could you find a solution?
