### ISSUE TITLE
Cannot fetch more than 15K tweets per request

### ISSUE THREAD

**Issue by FiratIsmailoglu** [jonbakerfish/TweetScraper#87]
Hi, thank you for this awesome hassle-free work. The only problem that I encounter is that the program allows me to get no more than 15 thousands tweets per request. In spite of my best effort, I have'nt been able to overcome this. So any thing that helps me solve this problem is more than welcome. Cheers.

**Comment by cihan-github** [comment]
I'm dealing with the same problem, have you found any solution? Or can someone help us? :D

**Comment by cihan-github** [comment]
Add DOWNLOAD_DELAY = 1 or DOWNLOAD_DELAY = 1.5 to the settings.py file. This solved my problem.
