### ISSUE TITLE
Looping the same tweets/readiness of scraper

### ISSUE THREAD

**Issue by coreyryanhanson** [jonbakerfish/TweetScraper#95]
When I try to use this module, it will pull a few dozen tweets from a query and then will get stuck adding nothing new (aside from a few unrelated/sponsored tweets)

I noticed in the code, self.url appears to make it's requests using the api https://api.twitter.com/2/search/adaptive.json which would defeat the purpose of a scraping module.

Is a temporary fix due to the recent changes that broke other scrapers? Also are there any plans for wait times and switching user agents?

**Comment by ASIAMI** [comment]
have a similar problem
on conda3 shell indicates about 2000 items have been collected
but there are 173 in the file
If anyone has a similar problem, please contact me

**Comment by aaryanwang** [comment]
I have same problem

**Comment by shiwenThu** [comment]
same problem

**Comment by aaryanwang** [comment]
@jonbakerfish，can you fix it?

**Comment by ChengzhiCU** [comment]
same problem

**Comment by xuzhijun528** [comment]
same problem

**Comment by Eilgnaw** [comment]
same problem
