### ISSUE TITLE
couldn't install install.sh

### ISSUE THREAD

**Issue by yangyangdotcom** [jonbakerfish/TweetScraper#97]
It might be my computer problem but when I run `bash install.sh` it gives me errors like this.

`install.sh: line 2: conda: command not found
: No such file or directoryangyang2202/.bashrc
install.sh: line 4: conda: command not found
install.sh: line 5: $'\r': command not found
install.sh: line 7: conda: command not found
install.sh: line 7: $'\r': command not found
install.sh: line 8: conda: command not found
install.sh: line 10: $'\r': command not found
install.sh: line 12: conda: command not found
install.sh: line 13: $'\r': command not found
[sudo] password for yangyang2202:
E: Invalid operation update
E: Command line option '
   ' [from -y
   ] is not understood in combination with the other options.
install.sh: line 17: pip: command not found`

Please help!

**Comment by ihahawen** [comment]
you can use "pip3 install -r requirement.txt"
