### ISSUE TITLE
failed to run "conda activate tweetscraper"

### ISSUE THREAD

**Issue by yangyangdotcom** [jonbakerfish/TweetScraper#99]
I am having a problem while running `conda activate tweetscraper`. It gives me error like this:
`Could not find conda environment: tweetscraper
You can list all discoverable environments with `conda info --envs`.`

**Comment by ihahawen** [comment]
you must install conda

**Comment by yangyangdotcom** [comment]
I believe I have conda installed because I can run conda info --envs
